#!/usr/bin/env bash

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$(cd "$SCRIPT_DIR/.." && pwd)"
CONFIGURATION_DIR="$REPO_ROOT/apps/ios/Configuration"
DESTINATION="$CONFIGURATION_DIR/Local.xcconfig"
TEMPORARY_FILE=""

cleanup() {
  local status=$?
  trap - EXIT
  if [[ -n "$TEMPORARY_FILE" && -f "$TEMPORARY_FILE" ]]; then
    rm -f -- "$TEMPORARY_FILE"
  fi
  exit "$status"
}
trap cleanup EXIT

if ! command -v gh >/dev/null 2>&1; then
  echo "error: GitHub CLI is required. Install 'gh' and authenticate before configuring iOS." >&2
  exit 1
fi

if ! gh auth status >/dev/null 2>&1; then
  echo "error: GitHub CLI is not authenticated. Run 'gh auth login' and try again." >&2
  exit 1
fi

if [[ ! -d "$CONFIGURATION_DIR" ]]; then
  echo "error: iOS configuration directory not found at $CONFIGURATION_DIR" >&2
  exit 1
fi

CLERK_PUBLISHABLE_KEY=""
if ! CLERK_PUBLISHABLE_KEY="$(
  cd "$REPO_ROOT"
  gh variable get VITE_CLERK_PUBLISHABLE_KEY --env production 2>/dev/null
)"; then
  echo "error: could not read VITE_CLERK_PUBLISHABLE_KEY from the GitHub production environment." >&2
  echo "Confirm repository access and that the Actions variable exists, then try again." >&2
  exit 1
fi

if [[ -z "$CLERK_PUBLISHABLE_KEY" ]]; then
  echo "error: the GitHub production VITE_CLERK_PUBLISHABLE_KEY variable is empty." >&2
  exit 1
fi

case "$CLERK_PUBLISHABLE_KEY" in
  *$'\n'* | *$'\r'*)
    echo "error: the Clerk publishable key contains an unexpected line break." >&2
    exit 1
    ;;
esac

case "$CLERK_PUBLISHABLE_KEY" in
  pk_live_*) ;;
  *)
    echo "error: the production GitHub variable is not a Clerk live publishable key." >&2
    exit 1
    ;;
esac

umask 077
TEMPORARY_FILE="$(mktemp "$CONFIGURATION_DIR/.Local.xcconfig.XXXXXX")"
{
  printf '%s\n' '// Generated by scripts/configure-ios.sh. This file is ignored by Git.'
  printf '%s\n' '// Re-run bun run configure:ios when the production Clerk key changes.'
  printf 'VOYAGE_CLERK_PUBLISHABLE_KEY = %s\n' "$CLERK_PUBLISHABLE_KEY"
} >"$TEMPORARY_FILE"
chmod 600 "$TEMPORARY_FILE"
mv -f -- "$TEMPORARY_FILE" "$DESTINATION"
TEMPORARY_FILE=""

echo "Configured the ignored iOS local settings at $DESTINATION."
echo "The Clerk publishable key was not printed."
